version: '3.9'
services:
  db_dev:
    image: "postgres:latest"
    environment:
      PGDATA: $PGDATA 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
    restart: unless-stopped
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - './db/seed.sql:/docker-entrypoint-initdb.d/init.sql'

  admin_dev:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD    
    restart: unless-stopped
    ports:
      - "5555:80"
    depends_on:
      - db_dev

  api_dev:
    image: ramyferhat59/cashmanager-deploy:api_dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    environment:
      POSTGRES_NAME: $POSTGRES_NAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      COMPOSE_PROJECT_NAME: $COMPOSE_PROJECT_NAME
      DOCKER_HUB_USER: $DOCKER_HUB_USER
      DOCKER_HUB_PASS: $DOCKER_HUB_PASS
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    depends_on:
      - db_dev

volumes:
  pgdata:  
